// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-order.ts
import { createClient } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/env.ts
function getSupabaseEnv() {
  const url = process.env.SUPABASE_URL;
  const serviceRole = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceRole) {
    throw new Error("Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  }
  return { url, serviceRole };
}

// src/lib/mcp/tools/get-order.ts
function adminClient() {
  const { url, serviceRole } = getSupabaseEnv();
  return createClient(url, serviceRole, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) return { ok: false, msg: "Not authenticated" };
  const uid = ctx.getUserId();
  if (!uid) return { ok: false, msg: "Missing user id" };
  const { data, error } = await adminClient().rpc("has_admin_access", { _user_id: uid });
  if (error) return { ok: false, msg: `Auth check failed: ${error.message}` };
  if (!data) return { ok: false, msg: "Admin access required" };
  return { ok: true };
}
var get_order_default = defineTool({
  name: "get_order",
  title: "Get order",
  description: "Look up a single order by its order number (e.g. SOA20260704-1234).",
  inputSchema: {
    order_number: z.string().trim().min(3).max(64).describe("Order number to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    const gate = await requireAdmin(ctx);
    if (!gate.ok) return { content: [{ type: "text", text: gate.msg }], isError: true };
    const { data, error } = await adminClient().from("orders").select("id, order_number, customer_name, customer_email, customer_phone, total_amount, status, created_at, razorpay_payment_id").eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No order found with number ${order_number}.` }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/get-sales-summary.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function adminClient2() {
  const { url, serviceRole } = getSupabaseEnv();
  return createClient2(url, serviceRole, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin2(ctx) {
  if (!ctx.isAuthenticated()) return { ok: false, msg: "Not authenticated" };
  const uid = ctx.getUserId();
  if (!uid) return { ok: false, msg: "Missing user id" };
  const { data, error } = await adminClient2().rpc("has_admin_access", { _user_id: uid });
  if (error) return { ok: false, msg: `Auth check failed: ${error.message}` };
  if (!data) return { ok: false, msg: "Admin access required" };
  return { ok: true };
}
var get_sales_summary_default = defineTool2({
  name: "get_sales_summary",
  title: "Get sales summary",
  description: "Aggregate sales metrics (orders count, revenue) for the last N days.",
  inputSchema: {
    days: z2.number().int().min(1).max(90).describe("Look-back window in days (1-90).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    const gate = await requireAdmin2(ctx);
    if (!gate.ok) return { content: [{ type: "text", text: gate.msg }], isError: true };
    const since = new Date(Date.now() - days * 864e5).toISOString();
    const { data, error } = await adminClient2().from("orders").select("total_amount, status, created_at").gte("created_at", since);
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    const paid = (data ?? []).filter((o) => o.status === "paid");
    const revenue = paid.reduce((s, o) => s + Number(o.total_amount || 0), 0);
    const summary = {
      window_days: days,
      total_orders: data?.length ?? 0,
      paid_orders: paid.length,
      revenue_inr: revenue
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/list-recent-orders.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.88.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function adminClient3() {
  const { url, serviceRole } = getSupabaseEnv();
  return createClient3(url, serviceRole, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin3(ctx) {
  if (!ctx.isAuthenticated()) return { ok: false, msg: "Not authenticated" };
  const uid = ctx.getUserId();
  if (!uid) return { ok: false, msg: "Missing user id" };
  const { data, error } = await adminClient3().rpc("has_admin_access", { _user_id: uid });
  if (error) return { ok: false, msg: `Auth check failed: ${error.message}` };
  if (!data) return { ok: false, msg: "Admin access required" };
  return { ok: true };
}
var list_recent_orders_default = defineTool3({
  name: "list_recent_orders",
  title: "List recent orders",
  description: "List the most recent orders, optionally filtered by status.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).describe("Number of orders (1-50)."),
    status: z3.enum(["pending", "paid", "failed", "partial_failure"]).optional().describe("Optional order status filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    const gate = await requireAdmin3(ctx);
    if (!gate.ok) return { content: [{ type: "text", text: gate.msg }], isError: true };
    let q = adminClient3().from("orders").select("order_number, customer_name, customer_email, total_amount, status, created_at").order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "hujuqkhbdptsdnbnkslo";
var mcp_default = defineMcp({
  name: "safal-online-mcp",
  title: "Safal Online Academy MCP",
  version: "0.1.0",
  instructions: "Admin tools for the Safal Online Academy portal. Requires an authenticated Supabase admin bearer token. Available tools: get_order, list_recent_orders, get_sales_summary.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated",
    // Accept Supabase user session tokens (mobile app signs in via Supabase Auth).
    // We enforce admin-only access inside every tool via has_admin_access RPC.
    requireOAuthClientClaim: false
  }),
  tools: [get_order_default, list_recent_orders_default, get_sales_summary_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
